---
- name: Restart traefik
  community.docker.docker_container:
    name: traefik
    restart: true

- name: Restart pihole dns
  community.docker.docker_container_exec:
    container: pihole
    argv:
      - pihole
      - restartdns
  delegate_to: "{{ item }}"
  loop: "{{ groups['pihole'] }}"

- name: Restart mosquitto
  ansible.builtin.service:
    name: mosquitto
    state: restarted

- name: Restart squid
  ansible.builtin.service:
    name: squid
    state: restarted
  when: not ansible_check_mode

- name: Restart prometheus
  community.docker.docker_container:
    name: prometheus
    restart: true

- name: Restart teleport
  community.docker.docker_container:
    name: teleport
    restart: true

- name: Restart newrelic
  ansible.builtin.service:
    name: newrelic-infra
    state: restarted

- name: Restart newrelic infra bundle
  community.docker.docker_container:
    name: newrelic.infra_bundle
    restart: true
