---
- name: Restart traefik
  community.docker.docker_container:
    name: traefik
    restart: true

- name: Restart pihole dns
  community.docker.docker_container_exec:
    container: pihole
    argv:
      - pihole
      - restartdns
