---
- name: Restart traefik
  community.docker.docker_container:
    name: traefik
    restart: true

- name: Restart pihole dns
  community.docker.docker_container_exec:
    container: pihole
    argv:
      - pihole
      - restartdns
  delegate_to: "{{ item }}"
  loop: "{{ groups['pihole'] }}"

- name: Restart mosquitto
  ansible.builtin.service:
    name: mosquitto
    state: restarted

- name: Restart squid
  ansible.builtin.service:
    name: squid
    state: restarted
  when: not ansible_check_mode
