---
- name: Restart logind
  ansible.builtin.service:
    name: systemd-logind
    state: restarted

- name: Reload udevadm
  ansible.builtin.command:
    cmd: udevadm control --reload
  changed_when: false

- name: Restart screen-saver
  ansible.builtin.service:
    name: screen-saver
    state: started
  when: not ansible_check_mode

- name: Restart docker
  ansible.builtin.service:
    name: docker
    state: restarted
  when: not ansible_check_mode

- name: Run exportfs
  ansible.builtin.command:
    argv:
      - exportfs
      - -arv
