---
- name: Ensure hass db user configured
  community.postgresql.postgresql_user:
    user: "{{ hass_db_user }}"
    password: "{{ hass_db_password }}"
    host: localhost
    login_user: "{{ postgres_user }}"
    login_password: "{{ postgres_password }}"
    state: present
  when: not ansible_check_mode

- name: Ensure hass database configured
  community.postgresql.postgresql_db:
    name: "{{ hass_db_name }}"
    host: localhost
    owner: "{{ hass_db_user }}"
    login_user: "{{ postgres_user }}"
    login_password: "{{ postgres_password }}"
  when: not ansible_check_mode
