- name: Ensure jellyfin vars loaded
  ansible.builtin.include_vars: jellyfin.yml

- name: Ensure jellyfin installed
  when: jellyfin
  block:
    - name: Ensure jellyfin image pulled
      community.docker.docker_image:
        name: "{{ jellyfin_image }}"
        source: pull

    - name: Ensure jellyfin container created
      community.docker.docker_container:
        state: started
        image_name_mismatch: recreate
        name: jellyfin
        image: "{{ jellyfin_image }}"
        restart_policy: always
        networks:
          - name: "{{ docker_network_name }}"
        env: "{{ jellyfin_env }}"
        ports:
          - 8096:8096
          - 8920:8920
          - 7359:7359/udp
        volumes:
          - /srv/jellyfin:/config
          - /tank/media:/media
        devices:
          - /dev/dri:/dev/dri
        labels:
          traefik.enable: "true"
          traefik.http.routers.jellyfin.entrypoints: websecure
          traefik.http.routers.jellyfin.rule: "Host(`jellyfin.{{ traefik_domain }}`)"
          traefik.http.services.jellyfin.loadbalancer.server.port: "8096"
          dockerdns.pihole.cname.domain: "jellyfin.{{ traefik_domain }}"
          dockerdns.pihole.cname.target: "{{ full_hostname }}"
