---
- name: Ensure music assistant vars included
  ansible.builtin.include_vars: music-assistant.yml

- name: Ensure music assistant facts configured
  ansible.builtin.set_fact:
    music_assistant_state: "{{ 'present' if music_assistant else 'absent' }}"

- name: Ensure music assistant image pulled
  community.docker.docker_image:
    name: "{{ music_assistant_image }}"
    source: pull
  when: music_assistant

- name: Ensure music assistant data dir configured
  ansible.builtin.file:
    path: "/srv/music-assistant"
    state: "{{ 'directory' if music_assistant else 'absent' }}"

- name: Ensure music assistant container configured
  community.docker.docker_container:
    state: "{{ 'started' if music_assistant else 'absent' }}"
    image_name_mismatch: recreate
    name: music-assistant
    image: "{{ music_assistant_image }}"
    restart_policy: always
    network_mode: host
    privileged: true
    volumes:
      - /srv/music-assistant:/data
    # labels:
    #  traefik.enable: "true"
    #  traefik.http.routers.music.entrypoints: websecure
    #  traefik.http.routers.music.rule: "Host(`music.{{ traefik_domain }}`)"
    #  traefik.http.services.music.loadbalancer.server.port: "8095"

- name: Ensure music assistant cname configured
  ansible.builtin.include_tasks: pihole-cname.yml
  vars:
    cname_domain: "music.{{ traefik_domain }}"
    cname_target: "{{ full_hostname }}"
  when: music_assistant
