---
# Areas
- name: area/docs
  color: "0e8a16"
- name: area/github
  color: "0e8a16"
- name: area/preflight
  color: "0e8a16"
- name: area/service
  color: "0e8a16"
- name: area/workstation
  color: "ffc300"
# Renovate Types
- name: renovate/container
  color: "027fa0"
- name: renovate/github-action
  color: "027fa0"
- name: renovate/grafana-dashboard
  color: "027fa0"
- name: renovate/github-release
  color: "027fa0"
# Semantic Types
- name: type/digest
  color: "ffeC19"
- name: type/patch
  color: "ffeC19"
- name: type/minor
  color: "ff9800"
- name: type/major
  color: "f6412d"
# Uncategorized
- name: community
  color: "370fb2"
- name: hold
  color: "ee0701"
