- name: Installs and configure nodes
  gather_facts: true
  hosts: all
  become: true
  become_user: root
  environment:
    NEW_RELIC_API_KEY: "{{ newrelic_api_key }}"
    NEW_RELIC_ACCOUNT_ID: "{{ newrelic_account_id }}"
    NEW_RELIC_REGION: "{{ newrelic_region }}"
  tasks:
    - name: Include preflight role
      ansible.builtin.include_role:
        name: preflight
      tags: always
    - name: Include service role
      ansible.builtin.include_role:
        name: service
      tags: always
    - name: Include workstation role
      ansible.builtin.include_role:
        name: workstation
      tags: always
