---
- name: Installs and configure nodes
  gather_facts: true
  hosts: server
  become: true
  become_user: root
  tasks:
    - name: Include service Role
      ansible.builtin.include_role:
        name: service
      tags: always
    - name: Ensure unused docker image pruned
      ansible.builtin.command:
        argv:
          - docker
          - image
          - prune
          - -a
          - -f
      changed_when: false
      tags: prune,always
