---
- name: Restore backup
  hosts: all
  become: true
  become_user: root
  gather_facts: true
  tasks:
    - name: Restore backup
      ansible.builtin.include_role:
        name: backup
        tasks_from: restore
