---
- name: Ensure pihole cname configured
  gather_facts: true
  hosts: pihole
  become: true
  become_user: root
  tasks:
    - name: Include service role
      ansible.builtin.include_role:
        name: service
        tasks_from: cname-update.yml
        apply:
          tags: always
      tags: always
    - name: Ensure cname local file removed
      ansible.builtin.file:
        path: "/srv/pihole-cname.conf"
        state: absent
      delegate_to: localhost
      tags: always
