---
collections:
  - ansible.posix
  - community.general
  - community.docker
  - community.sops
  - community.postgresql
  - bitwarden.secrets
roles:
  - name: geerlingguy.docker
  - name: geerlingguy.nfs
  - name: kilip.regolith
  - name: kilip.gpg
