version: 3

vars:
  ANSIBLE_BIN: "{{.VIRTUAL_ENV}}/bin/ansible"
  PLAYBOOK_BIN: "{{.VIRTUAL_ENV}}/bin/ansible-playbook"
  PLAYBOOK_CMD: "{{.PLAYBOOK_BIN}} -i {{.INVENTORY}}"

tasks:
  deps:
    desc: installs project dependencies
    cmds:
      - pass hp/age-key > age.key
      - task: deps:brew
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - ansible-galaxy collection install -r collections/requirements.yml
      - ansible-galaxy role install -r roles/requirements.yml

  deps:brew:
    desc: install brew dependencies
    cmds:
      - brew install sops
      - brew install age

  dev:converge:
    desc: molecule converge
    cmds:
      - molecule converge
    env:
      PLAYBOOK_TESTING: true

  dev:destroy:
    desc: molecule destroy
    cmds:
      - molecule destroy
      - molecule reset

  ping:
    desc: Ping all available hosts
    cmds:
      - "{{.ANSIBLE_BIN}} -i {{.INVENTORY}} --one-line -m ping all"

  check:
    desc: Check playbook run
    cmds:
      - task: play
        vars:
          CLI_ARGS: "--check {{.CLI_ARGS}}"

  play:
    desc: Run ansible playbook
    cmd: "{{.PLAYBOOK_BIN}} -i {{.INVENTORY}} {{.playbook}}{{.host}}{{.tags}}{{.check}}{{.args}}"
    vars:
      host: "{{if .host}} -l {{.host}}{{end}}"
      check: "{{if .check}} --check{{end}}"
      tags: "{{if .tags}} --tags {{.tags}}{{end}}"
      args: "{{if .CLI_ARGS}} {{.CLI_ARGS}}{{end}}"

  preflight:
    desc: Converge semaphore hosts
    cmds:
      - task: play
        vars:
          playbook: play-preflight.yml

  semaphore:
    desc: Converge semaphore hosts
    cmds:
      - task: play
        vars:
          host: semaphore
          tags: docker,semaphore

  workstation:
    desc: Play workstation tasks
    cmds:
      - task: play
        vars:
          playbook: play-workstation.yml

  service:
    desc: Play service tasks
    cmds:
      - task: play
        vars:
          playbook: play-service.yml

  monitoring:
    desc: Runs monitoring tasks
    cmds:
      - task: play
        vars:
          playbook: play-monitoring.yml

  test:
    desc: Runs testing playbook
    cmds:
      - task: play
        vars:
          playbook: play-test.yml

  reboot:
    desc: Reboot machine
    cmds:
      - task: play
        vars:
          playbook: play-reboot.yml

  backup:
    desc: Runs backup
    cmds:
      - task: play
        vars:
          playbook: play-backup.yml

  restore:
    desc: Runs restore
    cmds:
      - task: play
        vars:
          playbook: play-restore.yml
