ansible_host: ENC[AES256_GCM,data:EGVpgBEl3as8,iv:qFHK1qzri6GSD3HiO25nLI4v4Ytf5BDi+634IJVC6ig=,tag:K/Ii940infWWLowoq+5qfQ==,type:str]
ansible_python_interpreter: ENC[AES256_GCM,data:VRwNn1U5DiRr/z2rOe0AS/n1mQ==,iv:C3c6ocbTu9ObgiEIwmIKWubRLon31HkzDT4LfuS+oAk=,tag:vy8nt8+rN07md2LXdsS9Nw==,type:str]
hostname: ENC[AES256_GCM,data:varNew==,iv:4HPDYgtPtt4zMpfPUvH2SjzVtANyzfGwxwMVoExgwBM=,tag:lxOOmcCN65QGyIiYvuiE7g==,type:str]
full_hostname: ENC[AES256_GCM,data:i6hJRc10WHY=,iv:xLTg7bG9A8zC6Vc9l4vuWd1KbWZa2a2McVTUcpS6DCw=,tag:Tu3lTA33Ji/8sZ0Y39Wdhw==,type:str]
custom_packages:
    - ENC[AES256_GCM,data:6uIt7J1fvBRx,iv:WvzZms54h+KaxEnidQ001WUiLR4tFVGLURAb+pmeuTU=,tag:iutp3t1Da825z2iF/M60qQ==,type:str]
    - ENC[AES256_GCM,data:jfK1GZ7HLYauqQ/W,iv:wmBE/6n66KoErxLSkMhSpmgGdIr23HAB/b7MVCiO5e4=,tag:9DVtJu+pge61Oi7y0W/+ew==,type:str]
    - ENC[AES256_GCM,data:X5LXWx8=,iv:FyJogQJ8mnL8+Us9/gpKlXX9K3Jq/4fGFTvPoj+ZkUg=,tag:on9nHcB98MWFfCYfD5Yx4A==,type:str]
    - ENC[AES256_GCM,data:7/N4E/sceg==,iv:c8Ozo3VYLCHbAWl6WuJOnebm6l3EB4mLJL42rm/o7q4=,tag:7cE+Khy65u84J1hC9SIetA==,type:str]
    - ENC[AES256_GCM,data:+KjjFqTTFbiEV/cxrCBdlIneGL3yQ9eKTeUU,iv:huxnL0Di7C/MQspsglLeAQyhGyM16e7tUyq8f+xW3w0=,tag:NNXkAW2m5ZeVIjCeUCpKEA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13n6rctev7vwr2vuds9uqdh6anhvdvl2zt8gu9jp6mmvw2wukuqmqxz9ghv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQ1I1cG12Y25MNWpwR3VG
            cGx4QWhOTjZGa0hxUkJGODBMQWYveTZneGljClJVbXltYk1HakVwQW1RVmJnVXU3
            OHBCSzVqQi9xN3p6OXBGT1hlWXBKVm8KLS0tIFFxV0s0aExjcElVZ3hNS0dSU3Zw
            TVU3M2RpbVgvNFJoWXA0MURuU3hJZWMKOOJvuAydZAso2TvBgC2TmZVyCf9wPNiJ
            YfTPOncFn6d8HJEtSgZpREhsxI25YnhfhCcYSuZA9OohQ6j79c0v+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-16T11:52:53Z"
    mac: ENC[AES256_GCM,data:9ag3fFNBhk+ErZ5hliENURj62uHLs0BxMf7+eu8Z1nlGam8IRcEtVfeKTDBCRQgmv04PMiPZ9hb7FMnBXFYjDOioimOvAKuqc32kstHJRSpFdE8LJIxE3Lfancxx3i3xJGmrnrMVvti0miRz8ra70jRqo+dJU20LSeG+bRowgE0=,iv:27iSdZ8qEdhpSlnP6b2xwaHsrm5UJEcItebDSSVMX2E=,tag:3e0UNlmkUPpjNp/PrCdBoA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
