ansible_host: ENC[AES256_GCM,data:Gl36nqnBhPew,iv:S6ZWB1pbe8YcPlgEob9vDVi4mq+RsiEcNCsrIiCGtFU=,tag:RB+SXb7G5QhSS8Jix2wzBw==,type:str]
ansible_user: ENC[AES256_GCM,data:5GkB9w==,iv:Gac0R4NApULSJGliS9Z3TvBQ4P0T45tCzOIXtG11XdQ=,tag:MO09er4cMqAGO2MLb9Evnw==,type:str]
ansible_python_interpreter: ENC[AES256_GCM,data:lRAMTUcO2sfnLe460aw5TszKyg==,iv:1Iz7HLoVtfZ2t36bdVJDn4Zyha0XvnhASkzj8Ulu7XA=,tag:RVTK9a+uR2mMkJuZu3cXcQ==,type:str]
full_hostname: ENC[AES256_GCM,data:VA+OiTYTXck=,iv:Odtf8m0/X4t8yvOifoJcmt6mUale3MCfCw75Ys513h0=,tag:ne4TAfe3BBVNv6uPMoARdw==,type:str]
laptop: ENC[AES256_GCM,data:+8+gjg==,iv:WMVAxwLsYSyYlvDhucoMF/hukAvxX8rCiHd91+aJ07g=,tag:F/EaOColmOdU4YSEBrSgEw==,type:bool]
custom_packages:
    - ENC[AES256_GCM,data:4m2TGuEjtsNH+nku,iv:gNVFafez1MqJylA+6Zkm++QgYb9kk0XMZE9TB8MM9wk=,tag:Qu3W+Adn++1iWWr61ZeH3g==,type:str]
    - ENC[AES256_GCM,data:TRDyfzt/IpSZSjGCdidG,iv:wQaV92xOoYh8vqQn74XvKj0QaYQcuDhNEJXb5AQjQXI=,tag:xs8z7RAYqCN6GBL/EIyYbQ==,type:str]
    - ENC[AES256_GCM,data:5kgGlaoIDe4Xhd6ioo0bqlV8hYU=,iv:WN0yJMbSQ9H1V3z/jmA2mxI+cx6M59Iq1AZpyL8Ht30=,tag:tXuU4hqDo+92ZyRkGYMjsg==,type:str]
nfs: ENC[AES256_GCM,data:pMDHig==,iv:BoX8YKtsK6gbGpeuaOMQv8G6xQ+IRU4QhuR7ZJqTg2w=,tag:T/GcdYVMNGsuhUon6j2QIQ==,type:bool]
docker: ENC[AES256_GCM,data:aWCw1w==,iv:g7C1LcvOyUdVZHJL0Vo+LwR4TFfq4AkyEKbcxIBYJrE=,tag:47tHC8sD+mPeX4cn0UkK1A==,type:bool]
portainer_agent: ENC[AES256_GCM,data:o7Lrvg==,iv:Mv1aLQ9e6Dm6av6otHoaWHIrRsrIbIPgZQew0Nh7X8M=,tag:wFJAiuZrJxinQrbjQ9UnpQ==,type:bool]
brew: ENC[AES256_GCM,data:zTfczg==,iv:7JxCPusqDkSlnJqgfPfJ5iQExdJZtkWmPljitkbkkN8=,tag:fvSP/g/OEEs8ZA/nWIz5UQ==,type:bool]
brew_packages:
    - ENC[AES256_GCM,data:GLoliyL+kg==,iv:9jYXMUPZNC4eOKY9N6rBJAaPiC9GoPn0Y7V+/cSjPOE=,tag:TJSdw+EphlN6sANLWihG1Q==,type:str]
qbittorrent_download_dir: ENC[AES256_GCM,data:5bi75e1rZJHYbuM=,iv:ixM5/eDrANeeksL7AN4SrLcegrWCorBs99C1i7GwVgg=,tag:Owg5KATEzwQaUVl+LDMRbA==,type:str]
pyload_download_dir: ENC[AES256_GCM,data:CjlZK9SzGdG9F8Y=,iv:TLEzloLZco2UYjfM3cQlYQ5Zs/zlZQ8PJOaye3Im2UM=,tag:yWSZL95vMi/Hk543IHSgmA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13n6rctev7vwr2vuds9uqdh6anhvdvl2zt8gu9jp6mmvw2wukuqmqxz9ghv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQ1I1cG12Y25MNWpwR3VG
            cGx4QWhOTjZGa0hxUkJGODBMQWYveTZneGljClJVbXltYk1HakVwQW1RVmJnVXU3
            OHBCSzVqQi9xN3p6OXBGT1hlWXBKVm8KLS0tIFFxV0s0aExjcElVZ3hNS0dSU3Zw
            TVU3M2RpbVgvNFJoWXA0MURuU3hJZWMKOOJvuAydZAso2TvBgC2TmZVyCf9wPNiJ
            YfTPOncFn6d8HJEtSgZpREhsxI25YnhfhCcYSuZA9OohQ6j79c0v+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-13T06:37:35Z"
    mac: ENC[AES256_GCM,data:mMoJccUa9qKc+8aZXEJt+VvlX3yRqGJz3J1kLXAXFeJ87sEljTzAwdUUk5NsvM4sqiGWizwOZ5N1JvpFSG9HoHZGnfGUSzpyXA2iqLUcEoXf3a56aPECPqYClKZYJcU2AZDqdLH9f0N5WuMc/MTXlVi5C49yUl0SzW3D0sLTTZQ=,iv:xAdd7+ylu/kl6LHZ5093J7LWPahDEEAZQyi51wOpHNI=,tag:D6mhbXiWUkJWaLCcwUk+yA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
