ansible_host: ENC[AES256_GCM,data:64y6p0xLqXUI,iv:tNyyuZJLkWbxhXPnBiPJJEg4A6JKYQTDln2GDJr4fVw=,tag:GmYrrLoe2/aStUMmDC4uxQ==,type:str]
ansible_python_interpreter: ENC[AES256_GCM,data:5AtilyUWHxDY4Lj/R0pjB5T6JQ==,iv:rZ0eYrabMxYTqcwrmr+VsbONl7Lq8rShK4uaj92AJQU=,tag:HfHoUIwf8FpiuRLWUJAsbA==,type:str]
laptop: ENC[AES256_GCM,data:x78PtQ==,iv:Qissx7LGOq2lG7vVgMp/v93WItvVKeaPopX/JPvjaJk=,tag:ZNxz5ecSpJBh9fYWH1dVxQ==,type:bool]
docker: ENC[AES256_GCM,data:Dc6FRg==,iv:xQzXu59+0hy8w1LF2bRMEbMGjBsYr56qQidJrkEBhHc=,tag:mnzw7kc0TvVR//MBO+eH2A==,type:bool]
postgres: ENC[AES256_GCM,data:2iM8eg==,iv:L61dhvvhvZXh0chCwnSwx9TBJWqfod5RUTqzmg4AeCs=,tag:PG55qhMiHJ/fvWIlLt7cRg==,type:bool]
traefik: ENC[AES256_GCM,data:C7z9Iz0=,iv:O29BoavhNm3EWKu8hmxjBH4z7GEwT5+fCtqwCq84veQ=,tag:peZ6+nwUTGzXJdhg/yh7rA==,type:bool]
traefik_hostname: ENC[AES256_GCM,data:195XSA==,iv:NAET8Qyvs7OMJaWJ5EmdgGakgbNX/cGE0IEANWV5GNg=,tag:5zc6y0G9d8HUD/qbafwEoQ==,type:str]
portainer_agent: ENC[AES256_GCM,data:4imQ/Q==,iv:bO2ZWb2+bTbhmdHvNupITdDqjr0bNF5TYMa8gpAch10=,tag:Rl2+hn42oZX991VV+Wr8NQ==,type:bool]
hass: ENC[AES256_GCM,data:kA/e1Z8=,iv:8Ztyam09YjBNtJTf6V4rGr4efngNy9gmadBWIhocZ8o=,tag:zd7tlkH1fhdeMvgqJNK1NA==,type:bool]
hass_automation_enabled: ENC[AES256_GCM,data:C7SzTKI=,iv:JLI32lXs9zERudnYcHBpPg0G+t67YZgAm7HnX8+9lIs=,tag:wQXU8BBCSb2eQkT7DJDLSA==,type:bool]
nfs_server: ENC[AES256_GCM,data:0Yowkg==,iv:qW6gEzJeebuJhmv0nTm3MnTui1lzlrU8V98t9CLRORE=,tag:qygUJHs5ZTz/cVJpNlaqAg==,type:bool]
nfs_exports:
    - ENC[AES256_GCM,data:9kI34q51mh2vrcwJiUU6c0eLfC/+eT8t3uWwVWVKdjLIk9GX5NLiBb1wKZFT17HRi3ohZOS4N8ANKIC34XyPB6Qz4LNaD2v5tBNLxXjfKP38JpLQ5oYf,iv:CacJlsuGllxw/w0iX2RCBPZB+LsbSlBN48toNkw4UCE=,tag:y+YdUS6NcIukTbF8OYmbHQ==,type:str]
    - ENC[AES256_GCM,data:BrgyFvnUuFwoEUbNqMbQZXtd5aNVp0NA2VGzr0seqnkwfXBOVt/2KfCp14qgsP0Hv6R4J19bHp2HT8PtbD91hhNbHVaOCE94WbL6e55vPUVcfy9EGKwlwCWdWmS9,iv:Pmm9b2YN23TfslM40qw+uCzloshbJmhHt/z6bvtQ2sU=,tag:fWEn7++iNGgxPydJYZ3AHQ==,type:str]
postgres_host: ENC[AES256_GCM,data:nZjT3M2Pagpq,iv:q4O0PAi5jl7nIapTayUP+eIMZT0SiKor33QFdSItZF4=,tag:SDVEeVjdVcyZjCYlpKl7DA==,type:str]
squid: ENC[AES256_GCM,data:wHn7wA==,iv:HSwJqbnMEGpjsZvzleyzk95WyGv7aAPP/WHKGKzuFto=,tag:MbaTfNwNt9j+hYH5Nv3pPA==,type:bool]
squid_cache_dir: ENC[AES256_GCM,data:Bp0+mxL0nzuCBg==,iv:qNFh+fWkhb3Bxs2eEuAtGWpOja7RyftAq1SyCKPqJEk=,tag:tO4QWIU2KC7lIezs/qWZHw==,type:str]
tunnel: ENC[AES256_GCM,data:EmtCI20=,iv:HX7VkFfIvWjWqvEURTwAXhJHTmbjxpzJYIp0pJZauuM=,tag:Qcf6UUZEk+ysfTp3N1nMhg==,type:bool]
mosquitto: ENC[AES256_GCM,data:SD1HeA==,iv:zmVNdKhv+fXuBBD4UPpI9WGAT8Gyky0Pkmq37YO0THM=,tag:mTYF9wDoCXrj4uhJ1lxsdA==,type:bool]
backup_dir: ENC[AES256_GCM,data:XTjJ+ZWEqPep,iv:UYu4tJeOhL2ABZDNfyChD/fedL9OOUQaIuyGNslkBZI=,tag:3jyUxlXnpT12ciB1U8RyiA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13n6rctev7vwr2vuds9uqdh6anhvdvl2zt8gu9jp6mmvw2wukuqmqxz9ghv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQ1I1cG12Y25MNWpwR3VG
            cGx4QWhOTjZGa0hxUkJGODBMQWYveTZneGljClJVbXltYk1HakVwQW1RVmJnVXU3
            OHBCSzVqQi9xN3p6OXBGT1hlWXBKVm8KLS0tIFFxV0s0aExjcElVZ3hNS0dSU3Zw
            TVU3M2RpbVgvNFJoWXA0MURuU3hJZWMKOOJvuAydZAso2TvBgC2TmZVyCf9wPNiJ
            YfTPOncFn6d8HJEtSgZpREhsxI25YnhfhCcYSuZA9OohQ6j79c0v+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-11T14:19:23Z"
    mac: ENC[AES256_GCM,data:oUQ2FSRVY0l7IFKmYgeVv3gNEMszg2xJfV9zgI/CcHGGWdCjH/OMLbCntFf2pryr+uodyOEUo1kiIdIX/w82yv+w18/NFXRZ3lC+V288eJah+nD4/AGsqTnVwlSGdCHmLxSouIUfDWoZPjEPWUNOqYD1F2yboiSVy5CeOvWB1Fg=,iv:6l+gK0fXnQvNKzRZRqfFzLfjzjuCHjiFh1t6obiRJoc=,tag:nCKUidOO2GPmH5W5HCIeag==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
