ansible_host: ENC[AES256_GCM,data:64y6p0xLqXUI,iv:tNyyuZJLkWbxhXPnBiPJJEg4A6JKYQTDln2GDJr4fVw=,tag:GmYrrLoe2/aStUMmDC4uxQ==,type:str]
configure_laptop: ENC[AES256_GCM,data:c4XA8w==,iv:zfQsPauo8Iq+sM6HMvS7tHEE31uwbYOsAKyBQtOvGXg=,tag:pU1B0fPCxTjR9RQaksxaFg==,type:bool]
configure_docker: ENC[AES256_GCM,data:7EW+sA==,iv:AuE4ST5qxS+93+bhy6ucX12g+5YuvAe/t7xoIRTBdEM=,tag:BG6/ruCN3o8OBX+6vTe+6A==,type:bool]
postgres: ENC[AES256_GCM,data:2iM8eg==,iv:L61dhvvhvZXh0chCwnSwx9TBJWqfod5RUTqzmg4AeCs=,tag:PG55qhMiHJ/fvWIlLt7cRg==,type:bool]
traefik: ENC[AES256_GCM,data:IMdFSw==,iv:DaE5wNRVE7lO6G6R/O/WCyd7BHkyFYlcY//vvDGBpPQ=,tag:UDsN2c8iHP9GOKpmRR/sdQ==,type:bool]
traefik_hostname: ENC[AES256_GCM,data:YI8viw==,iv:YcFbDWoOPlGkhPezmBRO5pIeld+9WRGaUA6m8MDFo3Y=,tag:U9WpBZM9kAZ6O+cCVqCA+Q==,type:str]
portainer: ENC[AES256_GCM,data:pw5xlQ==,iv:TUQ8X4EUhZ5CBlhM2t1MOSWMpjT/wNrjGbVJq6nZOo0=,tag:R5/Yi46jg55KDt3VM3wBKQ==,type:bool]
portainer_edition: ENC[AES256_GCM,data:rxY=,iv:d5HqyBUfsd+uaeV3gNS1qANxsiPD+7Nrb5QMsc2Oaok=,tag:I0wcFFp3hwWHSInF570eHA==,type:str]
portainer_hostname: ENC[AES256_GCM,data:Kukylm2+kMka,iv:20OJS0dB28kbNog49Xtga1XQhM9AiEg/r7n0YwXcwSU=,tag:/43ZXv7ghcJ7MnEG7hfjLw==,type:str]
hass: ENC[AES256_GCM,data:9Ze3mQ==,iv:hMqu0OpGGXgZd8gLBbKjJtZPtykqDwx4HY3Tl3BjXd4=,tag:lx/M6IT9TJeULcJJgfrzpA==,type:bool]
hass_hostname: ENC[AES256_GCM,data:JBDePhtZ,iv:5cdKkoWlFcsiPBUT2jOvr2Rm7MRKnOkvMXWWtSY4RGc=,tag:UMjQcnsF9Zg/REkk0a0BmA==,type:str]
nfs_server: ENC[AES256_GCM,data:0Yowkg==,iv:qW6gEzJeebuJhmv0nTm3MnTui1lzlrU8V98t9CLRORE=,tag:qygUJHs5ZTz/cVJpNlaqAg==,type:bool]
nfs_exports:
    - ENC[AES256_GCM,data:9kI34q51mh2vrcwJiUU6c0eLfC/+eT8t3uWwVWVKdjLIk9GX5NLiBb1wKZFT17HRi3ohZOS4N8ANKIC34XyPB6Qz4LNaD2v5tBNLxXjfKP38JpLQ5oYf,iv:CacJlsuGllxw/w0iX2RCBPZB+LsbSlBN48toNkw4UCE=,tag:y+YdUS6NcIukTbF8OYmbHQ==,type:str]
    - ENC[AES256_GCM,data:BrgyFvnUuFwoEUbNqMbQZXtd5aNVp0NA2VGzr0seqnkwfXBOVt/2KfCp14qgsP0Hv6R4J19bHp2HT8PtbD91hhNbHVaOCE94WbL6e55vPUVcfy9EGKwlwCWdWmS9,iv:Pmm9b2YN23TfslM40qw+uCzloshbJmhHt/z6bvtQ2sU=,tag:fWEn7++iNGgxPydJYZ3AHQ==,type:str]
traefik_config: ENC[AES256_GCM,data:s4t1L8uSfqvAXarw8wM=,iv:eOd3FVKaiavq7nK6Zk63RdIpyUZkZx1fzacbgqkk6sE=,tag:YfoVuTLsWwZw4xW6PXIb0A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13n6rctev7vwr2vuds9uqdh6anhvdvl2zt8gu9jp6mmvw2wukuqmqxz9ghv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQ1I1cG12Y25MNWpwR3VG
            cGx4QWhOTjZGa0hxUkJGODBMQWYveTZneGljClJVbXltYk1HakVwQW1RVmJnVXU3
            OHBCSzVqQi9xN3p6OXBGT1hlWXBKVm8KLS0tIFFxV0s0aExjcElVZ3hNS0dSU3Zw
            TVU3M2RpbVgvNFJoWXA0MURuU3hJZWMKOOJvuAydZAso2TvBgC2TmZVyCf9wPNiJ
            YfTPOncFn6d8HJEtSgZpREhsxI25YnhfhCcYSuZA9OohQ6j79c0v+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-08T02:42:43Z"
    mac: ENC[AES256_GCM,data:iET2wSTmSUzxDni1QdQ2MR5Tm6od2dg3x4bw0AGtmlQjLH09qtcWJtnYY87XyodmYbpe+gJGEagSFKSdNQ9NEG82AwWNQ81zUsG6ix7kDRN4ZLGZSlIWA6RzVw01O8TmHgulPH4T6cWp3cxr3e7U41Y4xb+LhnW4CHtC4r+SVDY=,iv:33seLWQgCpU0nBW3gqqgc/L3I8CfC3RB2Ce5y0jTEz8=,tag:uyCodF2W8LeNoZBha2aAOw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
