ansible_host: ENC[AES256_GCM,data:kDK3kmGOhuU=,iv:iMSfV+dFG+dDIJB69cLGb+EdJZZblmmJAS6PiHh6eY8=,tag:CpTEKReycMTZmY4bd+zBHg==,type:str]
ansible_user: ENC[AES256_GCM,data:Nq5g8A==,iv:WgJDhPH/zj9Ws3km+H70N9sHl6zx+Uyd7zJNn9bVZcQ=,tag:WMkUlW23YuDoM8Oms2Xh1g==,type:str]
ansible_python_interpreter: ENC[AES256_GCM,data:ZY05EEWYZ/fwakwI2KJCmcMQ4g==,iv:i/Q0TyqKsPO4A/Dhs5NeYjeGF9baB1+ZtqhRgTezfqA=,tag:bwKSyt2nBSTQEkcDdd/IQA==,type:str]
user: ENC[AES256_GCM,data:N7C/pg==,iv:KZj6r0/z7Ezgzw6kcJZ57BVbQPsiUluSuc+pdMwO5uc=,tag:3GWtDASEkOuSj87F8zc+kg==,type:bool]
ssh: ENC[AES256_GCM,data:7RYG+g==,iv:+Agw2TcU6hk2jgrsym+dekQUBo4cmZ3Bhx4hnnMy9lM=,tag:3QAlGl/pW7QBl7dOTCiaWA==,type:bool]
password_store: ENC[AES256_GCM,data:IDDUYQ==,iv:Pw9lmMPy8B+Sb8odotV4MzyMl2Ab/20zc4Eewu89i64=,tag:8s3Mw+iHhlKCmMHC4C2nCA==,type:bool]
apt: ENC[AES256_GCM,data:kcxy/w==,iv:C0MO9iCqtkperPTjuEr/BWsMEGwm1NgiePT5tgtS07o=,tag:Q8rU/n12m7OvOAt6Zmy27g==,type:bool]
chezmoi: ENC[AES256_GCM,data:/6IFAQ==,iv:ckLuH7sWpaTCd1ACrwDqhocfQnPksP7+jZRt/oHbnMw=,tag:y7t245beyt1LPSU8PfFkBw==,type:bool]
starship: ENC[AES256_GCM,data:dEFJcQ==,iv:kuPSJ3Z0ZrDe2O/7tvAe5wgXkjEmmn54gUkPEskI+o4=,tag:PgPe+bd5etXthfW8g19BGQ==,type:bool]
docker: ENC[AES256_GCM,data:XzsXKQ==,iv:mH7eCBU2AZB85VhU2KWzd9paBKXpu+pSXpVqqrvwxVM=,tag:tOXh1oqhCJAhSlXFobIERQ==,type:bool]
regolith: ENC[AES256_GCM,data:tnvilw==,iv:dVK2g/xq1W1gfe6ACWGGBSwhtRnJbrB5acnNXfyCtBQ=,tag:5S1GEqPpBJ7jsXGZrZ1wQA==,type:bool]
openrgb: ENC[AES256_GCM,data:Xdx1bg==,iv:EeUdtzcF9IM7T6uMjNHF6Q1NyF0i1+FG/vm/u2b0Y9E=,tag:79hK4cPM2Hxnh9+xyEeb0g==,type:bool]
spotify: ENC[AES256_GCM,data:9e6Bsrg=,iv:wsuZ26wbKi3xpAAJ+6en/wLL62foxm5OcridbRDtNw8=,tag:orWz7kUvvnsVCZksVuVT/A==,type:bool]
brew: ENC[AES256_GCM,data:y6UdFg==,iv:m363jCSNdzOejPHLii9IbehYOdtpqLCMLvEVvdCWmzQ=,tag:jcwvwNKyCliFuJtqVrPlCw==,type:bool]
brew_taps:
    - ENC[AES256_GCM,data:R2dzEV/LlAKloap0unll,iv:Z69+Jv/xfAlgXA3vQF7n2qKQ+/p22tKymjIbHyMv7Ws=,tag:LjuidS31bLko/eb4IpPdNA==,type:str]
brew_packages:
    - ENC[AES256_GCM,data:zr0ALHY9AEgd+Zk=,iv:lw192PmAwtCPsEZWI1l+O3i6NRHiCs3M+dgHtZB51kM=,tag:uzg8lzwQYMmqAn4nAlCofw==,type:str]
    - ENC[AES256_GCM,data:LRVMs7AwhA==,iv:veygp1oAQvEt8Q7Q7JuzXy4j09NkZX1IeG2Ars/OPEM=,tag:yjStPyCJYVMmOVTnF5CgSA==,type:str]
    - ENC[AES256_GCM,data:oA0lw0tnlWS+i61b,iv:PDPFLhfKziSqfGWOP6o/9RNA/FytMd0bMreG2LAbMP8=,tag:QQ0lfdkJCgLjBo4G5S7rbw==,type:str]
    - ENC[AES256_GCM,data:kojMvfBu4b8=,iv:JIqvhPvNtg2htEumIOrFSgLuXf9i9zltExJS1WwSF3c=,tag:nVY5MR37If7gKPgAsJA4Sw==,type:str]
deepcool: ENC[AES256_GCM,data:mJ0xVA==,iv:j8TCDu26LvbA4tXywCYFtseGKuD4WAYD3apKareDjq0=,tag:b7Mjl8Z1SyykZdX4hITqAw==,type:bool]
pgadmin: ENC[AES256_GCM,data:vZhFXg==,iv:irLan+9V74aLbX8OWlS5FLGeKrklAwQgA4/vwe6wxkc=,tag:p3UQPXEj1lBNhh1boOwHPQ==,type:bool]
snap_packages:
    - ENC[AES256_GCM,data:W5LsUEAl1r8GOvBtzJpKpw==,iv:VWk+AYxEUfCcwogJZRzpYnxQNxYuBA4E/zOH6wHqKk4=,tag:mfn3NhrW5OQ7SJs6fIW04Q==,type:str]
nitrogen: ENC[AES256_GCM,data:x1jtIw==,iv:D385U85C9Z2jCze+KilP6mzUE0Ut7Rv16p4Tf9+zY5o=,tag:uc1mgFm0ZXp919eioIF1+g==,type:bool]
nitrogen_wallpaper: ENC[AES256_GCM,data:gmChQ6oMIgLR1n42AtHn6eoKcNL17kYQ/DmzVrBF3A==,iv:800d1wc6BS88pkLoK16r7kApDUO3k8imKV/2DJo4wI4=,tag:vi/yFs17lTDmzdSRo1A7zA==,type:str]
sops:
    age:
        - recipient: age13n6rctev7vwr2vuds9uqdh6anhvdvl2zt8gu9jp6mmvw2wukuqmqxz9ghv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQ1I1cG12Y25MNWpwR3VG
            cGx4QWhOTjZGa0hxUkJGODBMQWYveTZneGljClJVbXltYk1HakVwQW1RVmJnVXU3
            OHBCSzVqQi9xN3p6OXBGT1hlWXBKVm8KLS0tIFFxV0s0aExjcElVZ3hNS0dSU3Zw
            TVU3M2RpbVgvNFJoWXA0MURuU3hJZWMKOOJvuAydZAso2TvBgC2TmZVyCf9wPNiJ
            YfTPOncFn6d8HJEtSgZpREhsxI25YnhfhCcYSuZA9OohQ6j79c0v+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-06T15:53:43Z"
    mac: ENC[AES256_GCM,data:E3/4TgHScrjFIDP8/SjJbjqAuVWi+FvYVOYg52jywTQSFvksDISDXmWvHCXxYyFigGR7Wsda1sSbtF8AvWVcwHN83QKwCM7/azqp13AF4T789XZp9RJl4kOhwpphBpPRrhc/fC5C1yoFoJbiG6Dff1vPzGR+TcQeAL7bk+5mytU=,iv:Eo1gZo4cfP/g4qkZi/GQwGA6vw56OgZ8gwpfZCf9hjY=,tag:J0w/Lt+jQQb7NJT6k6livA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
