---
- name: Ensure data source configured
  community.grafana.grafana_datasource:
    name: Prometheus
    ds_type: prometheus
    ds_url: "http://prometheus:9090"
    access: proxy
    additional_json_data:
      timeInterval: 1m
    is_default: true
    url: https://grafana.itstoni.com
    grafana_api_key: "{{ grafana_api_key }}"
    state: present

- name: Ensure node exporter dashboard configured
  community.grafana.grafana_dashboard:
    grafana_url: https://grafana.itstoni.com
    grafana_api_key: "{{ grafana_api_key }}"
    dashboard_id: 1860
    dashboard_revision: 37
    overwrite: true
    state: present

- name: Ensure postgresql dashboard configured
  community.grafana.grafana_dashboard:
    grafana_url: https://grafana.itstoni.com
    grafana_api_key: "{{ grafana_api_key }}"
    dashboard_id: 9628
    dashboard_revision: 7
    overwrite: false
    state: present
