---
squid: false
squid_cache_dir_config: cache_dir aufs /var/spool/squid 20000 24 256

postgres: false
postgres_name: postgres
postgres_user: homeplay
postgres_password: homeplay
postgres_db: homeplay
postgres_data_dir: "/srv/postgres"

docker: false
docker_network_name: homeplay
docker_network_type: bridge
docker_network_exists: false

portainer: false
portainer_edition: ce
portainer_agent: false

traefik: false
# renovate: datasource=docker depName=traefik
traefik_version: v3.3.1
traefik_image: "traefik:{{ traefik_version }}"
traefik_dir: /srv/traefik
traefik_domain: itstoni.com
traefik_username: admin
traefik_hashed_password: change_me
traefik_hostname: traefik
traefik_cert_dir: "{{ traefik_dir }}/certs"
traefik_secret_dir: "{{ trefik_dir }}/secret"
traefik_ca_server: https://acme-staging-v02.api.letsencrypt.org/directory
traefik_ca_storage: /certs/acme-staging.json
traefik_config: false
cloudflare_email: admin@homeplay.com
cloudflare_token: replace_with_your_cloudflare_token

hass: false
# renovate: datasource=docker depName=linuxserver/homeassistant
hass_version: 2024.12.5
hass_image: "linuxserver/homeassistant:{{ hass_version }}"
hass_config_local_dir: /srv/hass
hass_config_branch: main
hass_config_repo: false
hass_deploy_key: false
hass_hostname: "hass"
hass_db_user: hass
hass_db_password: hass
hass_db_name: hass
hass_db_port: 5432
hass_db_host: postgres
hass_devices: []

# nfs server section
nfs_server: false


# pihole section
pihole: false
# renovate: datasource=docker depName=pihole/pihole
pihole_version: 2024.07.0
pihole_image: "pihole/pihole:{{ pihole_version }}"
pihole_dir: "/srv/pihole"
pihole_cname_file: "/srv/pihole/dnsmasq.d/05-pihole-custom-cname.conf"

semaphore: false
# renovate: datasource=docker depName=ghcr.io/kilip/semaphore
semaphore_version: v2.11.2
semaphore_image: "ghcr.io/kilip/semaphore:{{ semaphore_version }}"
semaphore_dir: /srv/semaphore
semaphore_db_name: semaphore
semaphore_db_user: semaphore
semaphore_db_pass: semaphore
semaphore_admin: admin
semaphore_admin_password: admin
semaphore_admin_name: Semaphore
semaphore_admin_email: admin@example.com
semaphore_email_sender: admin@example.com
semaphore_email_host: smtp.example.com
semaphore_email_port: 547
semaphore_email_username: admin@example.com
semaphore_email_password: password
semaphore_email_secure: 'true'

mosquitto: false

tunnel: false
tunnel_env: {}
# renovate: datasource=docker depName=cloudflare/cloudflared
tunnel_version: 2024.12.2
tunnel_image: "cloudflare/cloudflared:{{ tunnel_version }}"

jellyfin: false
mass: false
mass_volumes:
  - "/srv/mass/data:/data"

prometheus: false
# renovate: datasource=docker depName=prom/prometheus
prometheus_version: v3.1.0
prometheus_image: "prom/prometheus:{{ prometheus_version }}"

grafana: false
# renovate: datasource=docker depName=grafana/grafana-oss
grafana_version: 11.4.0
grafana_image: "grafana/grafana-oss:{{ grafana_version }}"
grafana_db_name: grafana
grafana_db_user: grafana
grafana_db_pass: grafana
grafana_db_host: postgres
grafana_db_port: 5432
grafana_db_type: postgres
grafana_api_key: false

portainer_agent_port: "9001"
minio_env: {}
minio_dir: '/srv/minio'

nextcloud: false
nextcloud_config_dir: "/srv/nextcloud/config"
nextcloud_data_dir: "/srv/nextcloud/data"

pgadmin: false
pgadmin_dir: '/srv/pgadmin'

authentik: false
authentik_dir: '/srv/authentik'

teleport: false
teleport_dir: '/srv/teleport'

influxdb: false
influxdb_dir: /srv/influxdb

telegraf: false
telegraf_dir: /srv/telegraf
