---
- name: Ensure brew packages installed
  become: true
  become_user: "{{ homeplay_user }}"
  block:
    - name: Ensure brew taps installed
      community.general.homebrew_tap:
        name: "{{ item }}"
        state: present
      with_items: "{{ brew_taps }}"

    - name: Ensure brew packages installed
      community.general.homebrew:
        name: "{{ brew_packages }}"
        state: present
