---
- name: Ensure apt key installed
  ansible.builtin.apt_key:
    url: https://archive.regolith-desktop.com/regolith.key
    state: present
    keyring: /usr/share/keyrings/regolith-archive-keyring.gpg

- name: Ensure apt source configured
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/regolith-archive-keyring.gpg] https://archive.regolith-desktop.com/ubuntu/stable noble v3.2
    state: present
    filename: regolith

- name: Ensure regolith packages installed
  ansible.builtin.apt:
    package:
      - regolith-desktop
      - regolith-session-flashback
      - regolith-look-dracula
      - regolith-compositor-picom-glx
      - i3xrocks-focused-window-name
      - i3xrocks-rofication
      - i3xrocks-info
      - i3xrocks-app-launcher
      - i3xrocks-memory
      - i3xrocks-cpu-usage
      - i3xrocks-temp
    update_cache: true
    state: present
