---
- name: Ensure required backup apps installed
  ansible.builtin.apt:
    package:
      - postgresql-client
      - rsync
    state: present
  delegate_to: "{{ backup_node }}"

- name: Ensure hass service backup
  ansible.builtin.include_tasks:
    file: backup/hass.yml
  when: backup_hass

# - name: Ensure backup synced
#  tags: synchronize
#  ansible.posix.synchronize:
#    src: "{{ backup_dir }}/"
#    dest: "{{ backup_rsync_dest }}/{{ inventory_hostname }}"
#    recursive: true
#    delete: true
#  delegate_to: "{{ inventory_hostname }}"
