---
- name: Ensure required backup apps installed
  ansible.builtin.apt:
    package:
      - postgresql-client
    state: present

- name: Ensure hass service backup
  ansible.builtin.include_tasks:
    file: backup/hass.yml
  when: hass

- name: Ensure backup synced
  tags: synchronize
  ansible.posix.synchronize:
    src: "{{ backup_dir }}/"
    dest: "{{ backup_rsync_dest }}/{{ inventory_hostname }}"
    recursive: true
    delete: true
  delegate_to: "{{ inventory_hostname }}"
