---
- name: Ensure required package installed
  ansible.builtin.apt:
    package:
      - postgresql-common
    state: present

- name: Ensure apt key imported
  ansible.builtin.get_url:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    dest: /usr/share/keyrings/postgresql.asc

- name: Ensure postgres apt source configured
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/postgresql.asc] https://apt.postgresql.org/pub/repos/apt {{ ansible_lsb.codename }}-pgdg main
    state: present
    filename: postgresql.list
    update_cache: true

- name: Ensure postgres client installed
  ansible.builtin.apt:
    package:
      - postgresql-16-client
    state: present
