---
- name: Ensure required restore apps installed
  ansible.builtin.apt:
    package:
      - postgresql-client
      - rsync
    state: present

- name: Ensure hass restore tasks included
  ansible.builtin.include_tasks:
    file: restore/hass.yml
  when: hass_restore.config and hass_restore.db
