---
- name: Ensure semaphore facts configured
  ansible.builtin.set_fact:
    semaphore_db_name: "{{ semaphore_env.SEMAPHORE_DB_NAME }}"
    semaphore_db_user: "{{ semaphore_env.SEMAPHORE_DB_USER }}"
    semaphore_db_pass: "{{ semaphore_env.SEMAPHORE_DB_PASS }}"
    semaphore_db_host: "{{ semaphore_env.SEMAPHORE_DB_HOST }}"

- name: Ensure semaphore image pulled
  community.docker.docker_image:
    name: "{{ semaphore_image }}"
    source: pull

- name: Ensure semaphore persistent dir exists
  ansible.builtin.file:
    path: "{{ semaphore_dir }}/{{ item }}"
    state: directory
    owner: 1001
    group: root
    mode: "0755"
  with_items:
    - config
    - data
    - tmp

- name: Ensure python requirements copied
  ansible.builtin.copy:
    src: requirements.txt
    dest: /srv/semaphore/config/requirements.txt
    owner: 1001
    group: root
    mode: "0644"

- name: Ensure semaphore postgres database configured
  ansible.builtin.include_tasks: postgres-db.yml
  vars:
    db_user: "{{ semaphore_db_user }}"
    db_pass: "{{ semaphore_db_pass }}"
    db_host: "{{ semaphore_db_host }}"
    db_name: "{{ semaphore_db_name }}"
  when: hass

- name: Ensure semaphore container configured
  community.docker.docker_container:
    state: started
    image_name_mismatch: recreate
    name: semaphore
    image: "{{ semaphore_image }}"
    networks:
      - name: "{{ docker_network_name }}"
    restart_policy: always
    env: "{{ semaphore_env }}"
    ports:
      - 3000:3000
    volumes:
      - "{{ semaphore_dir }}/data:/var/lib/semaphore"
      - "{{ semaphore_dir }}/config:/etc/semaphore"
      - "{{ semaphore_dir }}/tmp:/tmp/semaphore"
    labels:
      traefik.enable: "true"
      traefik.http.routers.semaphore.entrypoints: websecure
      traefik.http.routers.semaphore.rule: "Host(`semaphore.{{ traefik_domain }}`)"
      traefik.http.services.semaphore.loadbalancer.server.port: "3000"
      dockerdns.pihole.cname.domain: "semaphore.{{ traefik_domain }}"
      dockerdns.pihole.cname.target: "{{ full_hostname }}"
