---
- name: Ensure installation proxy config removed
  ansible.builtin.file:
    path: /etc/apt/apt.conf.d/90curtin-aptproxy
    state: absent

- name: Ensure apt proxy configured
  ansible.builtin.template:
    src: "apt-proxy.conf.j2"
    dest: "/etc/apt/apt.conf.d/99-proxy.conf"
    mode: "0775"
    owner: "root"
    group: "root"
  when: apt_proxy

- name: Ensure apt updated
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: true

- name: Ensure preflight packages installed
  ansible.builtin.apt:
    name: "{{ apt_packages + custom_packages }}"
    state: present
