---
- name: Ensure curl installed
  ansible.builtin.apt:
    package:
      - curl
    state: present

- name: Check if chezmoi installed
  ansible.builtin.stat:
    path: "{{ chezmoi_bin }}"
  register: chezmoi_bin

- name: Ensure chezmoi downloaded
  ansible.builtin.get_url:
    url: "http://get.chezmoi.io"
    dest: /tmp/chezmoi.sh
    mode: "0775"
  when: not chezmoi_bin.stat.exists

- name: Ensure chezmoi installed
  ansible.builtin.command:
    cmd: sh -c /tmp/chezmoi.sh
    creates: "/usr/bin/chezmoi"
    chdir: /usr

- name: Ensure chezmoi initialized
  become: true
  become_user: "{{ homeplay_user }}"
  block:
    - name: Ensure sops key dir exists
      ansible.builtin.file:
        path: "{{ homeplay_user_home }}/.config/sops/age"
        state: directory

    - name: Ensure sops key file generated
      ansible.builtin.shell:
        cmd: "pass show age/keys >> {{ homeplay_user_home }}/.config/sops/age/keys.txt"
        creates: "{{ homeplay_user_home }}/.config/sops/age/keys.txt"
      register: result
      when: chezmoi_use_age_key

    - name: Ensure chezmoi initialized
      ansible.builtin.command:
        cmd: "chezmoi init --force --apply {{ chezmoi_repo }}"
        creates: "{{ homeplay_user }}/.config/chezmoi/chezmoi.yaml"
