---
- name: Configure and install apt packages
  ansible.builtin.include_tasks:
    file: apt.yml
    apply:
      tags: apt
  tags: apt
  when: configure_apt

- name: Ensure locale configured
  ansible.builtin.include_tasks:
    file: locale.yml
    apply:
      tags: locale
  tags: locale
  when: configure_locale

- name: Ensure user configured
  ansible.builtin.include_tasks:
    file: user.yml
    apply:
      tags: user
  tags: user
  when: configure_user

- name: Configure ssh
  ansible.builtin.include_tasks:
    file: ssh.yml
    apply:
      tags: ssh
  tags: ssh
  when: configure_ssh

- name: Ensure gpg keys imported
  ansible.builtin.include_tasks:
    file: gpg.yml
    apply:
      tags: gpg
  tags: gpg
  with_items: "{{ gpg_keys }}"
  when: not ansible_check_mode

- name: Ensure pass configured
  ansible.builtin.include_tasks:
    file: pass.yml
    apply:
      tags: pass
  tags: pass
  when: configure_pass

- name: Ensure chezmoi configured
  ansible.builtin.include_tasks:
    file: chezmoi.yml
    apply:
      tags: chezmoi
  when:
    - configure_chezmoi
    - configure_ssh
    - configure_user
  tags: chezmoi

- name: Ensure laptop servers configured
  ansible.builtin.include_tasks:
    file: laptop.yml
    apply:
      tags: laptop
  tags: laptop
  when: configure_laptop

- name: Ensure starship configured
  ansible.builtin.include_tasks:
    file: starship.yml
    apply:
      tags: starship
  tags: starship
  when: configure_starship and not ansible_check_mode

- name: Ensure docker installed
  ansible.builtin.include_role:
    name: geerlingguy.docker
    apply:
      tags: docker
  when: configure_docker
  tags: docker
