---
- name: Ensure postgres tasks included
  ansible.builtin.include_tasks:
    file: postgres.yml
    apply:
      tags: postgres
  when: postgres
  tags: postgres

- name: Ensure minio tasks included
  ansible.builtin.include_tasks:
    file: minio.yml
    apply:
      tags: minio
  tags: minio

- name: Ensure dragonfly tasks included
  ansible.builtin.include_tasks:
    file: dragonfly.yml
    apply:
      tags: dragonfly
  tags: dragonfly

- name: Ensure redis tasks included
  ansible.builtin.include_tasks:
    file: redis.yml
    apply:
      tags: redis
  tags: redis

- name: Ensure nextcloud tasks included
  ansible.builtin.include_tasks:
    file: nextcloud.yml
    apply:
      tags: nextcloud
  tags: nextcloud

- name: Ensure pgadmin tasks included
  ansible.builtin.include_tasks:
    file: pgadmin.yml
    apply:
      tags: pgadmin
  tags: pgadmin

- name: Ensure mysql tasks included
  ansible.builtin.include_tasks:
    file: mysql.yml
    apply:
      tags: mysql
  tags: mysql
