---
- name: Ensure nextcloud vars included
  ansible.builtin.include_vars: nextcloud.yml

- name: Ensure nextcloud configured
  when: nextcloud
  block:
    - name: Ensure nextcloud db configured
      ansible.builtin.include_tasks: postgres-db.yml
      vars:
        db_user: "{{ nextcloud_env.POSTGRES_USER }}"
        db_pass: "{{ nextcloud_env.POSTGRES_PASSWORD }}"
        db_host: "{{ nextcloud_env.POSTGRES_HOST }}"
        db_name: "{{ nextcloud_env.POSTGRES_DB }}"

    - name: Ensure nextcloud config dir exists
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ homeplay_user }}"
        group: "{{ homeplay_user }}"
        mode: "770"
      with_items:
        - "{{ nextcloud_config_dir }}"
        - "{{ nextcloud_data_dir }}"

    - name: Ensure nextcloud image pulled
      community.docker.docker_image:
        name: "{{ nextcloud_image }}"
        source: pull

    - name: Ensure nextcloud container started
      community.docker.docker_container:
        name: nextcloud
        state: started
        image_name_mismatch: recreate
        image: "{{ nextcloud_image }}"
        env: "{{ nextcloud_env }}"
        volumes:
          - "{{ nextcloud_config_dir }}:/config:rw"
          - "{{ nextcloud_data_dir }}:/data:rw"
        restart_policy: always
        networks:
          - name: "{{ docker_network_name }}"
        ports:
          - 8443:443
          - 8080:80
        labels:
          traefik.enable: "true"
          traefik.http.routers.nextcloud.entrypoints: websecure
          traefik.http.routers.nextcloud.rule: "Host(`cloud.{{ traefik_domain }}`)"
          traefik.http.services.nextcloud.loadbalancer.server.port: "80"
          # traefik.http.routers.nextcloud.middlewares: 'nextcloud_redirectregex'
          # traefik.http.middlewares.nextcloud_redirectregex.redirectregex.permanent: "true"
          # traefik.http.middlewares.nextcloud_redirectregex.redirectregex.regex: 'https://(.*)/.well-known/(?:card|cal)dav'
          # traefik.http.middlewares.nextcloud_redirectregex.redirectregex.replacement: 'https://$${1}/remote.php/dav'

- name: Ensure nextcloud cname configured
  ansible.builtin.include_tasks: pihole-cname.yml
  vars:
    cname_domain: "cloud.{{ traefik_domain }}"
    cname_target: "{{ full_hostname }}"
    state: "present"
  when: nextcloud

- name: Ensure nextcloud cleaned up
  when: not nextcloud
  block:
    - name: Ensure nextcloud container removed
      community.docker.docker_container:
        name: nextcloud
        state: absent

    - name: Ensure nextcloud image removed
      community.docker.docker_image:
        name: "{{ nextcloud_image }}"
        state: absent

    - name: Ensure nextcloud directory removed
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
        owner: "www-data"
        group: "www-data"
      with_items:
        - "{{ nextcloud_config_dir }}"
        - "{{ nextcloud_data_dir }}"
