---
- name: Ensure postgres vars included
  ansible.builtin.include_vars: postgres.yml

- name: Ensure python postgres lib installed
  ansible.builtin.apt:
    name:
      - python3-psycopg2
      - python3-requests
    state: present
  tags: always

- name: Ensure postgres image pulled
  community.docker.docker_image:
    name: "{{ postgres_image }}"
    source: pull

- name: Ensure postgres container created
  community.docker.docker_container:
    state: started
    image_name_mismatch: recreate
    name: "{{ postgres_name }}"
    image: "{{ postgres_image }}"
    restart_policy: always
    env:
      POSTGRES_USER: "{{ postgres_user }}"
      POSTGRES_PASSWORD: "{{ postgres_password }}"
      POSTGRES_DB: "{{ postgres_db }}"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "{{ postgres_data_dir }}:/var/lib/postgresql/data"
    ports:
      - "{{ postgres_port }}"
    networks:
      - name: "{{ docker_network_name }}"

- name: Ensure postgres metrics container created
  community.docker.docker_container:
    state: started
    image_name_mismatch: recreate
    name: "postgres-exporter"
    image: "{{ postgres_exporter_image }}"
    restart_policy: always
    env:
      DATA_SOURCE_URI: "localhost:5432"
      DATA_SOURCE_USER: "{{ postgres_user }}"
      DATA_SOURCE_PASSWORD: "{{ postgres_password }}"
    ports:
      - 9187:9187
    networks:
      - name: "{{ docker_network_name }}"
