#ENC[AES256_GCM,data:TA9kCJ5Xxdt0uwh47s7HdpTYZA==,iv:PiVZCoKXAlpOmnv25hW8HXSl3rp9H/G776upgOhIWUc=,tag:zzfWjd9UqJGbhHBXwkRdbg==,type:comment]
http:
    routers:
        music:
            rule: ENC[AES256_GCM,data:fLYV8p7pTzJ5JpPbx/VacK59kDMSAvHMHA==,iv:sjdi6U9s+mNp8rYzNUlQqqjSpGEz9Xa4adRB60JA7vc=,tag:YOMX8UjEpbY6wK+TuCH4/A==,type:str]
            entrypoints: ENC[AES256_GCM,data:tFtTy931S/VU,iv:LrvEPW1enrpxJbL0eMtEn2SmXNyjIwksZl4kf23kB98=,tag:4L4QO+1/byf2qLyf+NjWFw==,type:str]
            service: ENC[AES256_GCM,data:NFEPVEc=,iv:fik6Rt65L5Hd8KBTjANW7SofY9JJYPOYnJ660VJjHA4=,tag:Mb0ZUrohX1jwjYM/DxXKWw==,type:str]
    services:
        music:
            loadBalancer:
                passHostHeader: ENC[AES256_GCM,data:/Mk1tA==,iv:awTrNFQxiVAYHOk87/8dnog7aKvFZcF/PEdtNvZzRxo=,tag:QanVG0sEJhDYbfovnwJiQg==,type:bool]
                servers:
                    - url: ENC[AES256_GCM,data:R4JZK+OMSgzTWsO0n0A8aHA48WzO,iv:WiL4nzV/XkGJDzLqZIFDLqZthJd07ntWsJHNq7xWh7A=,tag:7aWwAMzRWyBHq44hrVqxsQ==,type:str]
#ENC[AES256_GCM,data:7PJ7x0MMhs63lASndSwwdmEqtwm1,iv:Yg+Tplnl4MCYAc6LUPCyxCUIeXK8gL/pbW5YUu1DUjk=,tag:w7Utubc5IJkbNA4G8iz+Jg==,type:comment]
#ENC[AES256_GCM,data:v0deZz/34hN3jaBMs1u81jaQ,iv:CLUEhjeGY+cQ8Noc4f/pvPkyV8fg069MtcdVb8xNaG4=,tag:VYUtjz+sjJIz2I5SfVJJyA==,type:comment]
#ENC[AES256_GCM,data:+K5otxahD4BlIf+k4GVWbMPuTB4AwAFv08Pf2n1xxG3lzePn,iv:b4i79N6hke0uY10E9t5DgY4exGrhWuvT09MwLcO5HlQ=,tag:DQnOkrZh94EapQpQfDOg+g==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13n6rctev7vwr2vuds9uqdh6anhvdvl2zt8gu9jp6mmvw2wukuqmqxz9ghv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFUlpWNkNkZUNBVm5lcmRt
            MGVIdkQzcDZuNWJRNHVaYTl6VTdFMm9qcDFrCko1YXMrRlp5bSt3Nm1BK2VhWncr
            N1N4MGdoNXYrSU9hN3lycGJna3BYejgKLS0tIGk1dk8rcWNCTUQ4T1lBM2lPZ251
            ZEtVekJXTE9RZUFZa3FVQTNEeUZrd2cKYTn+vYnvu6RUrPKvQn0QE5PrCruSYCpD
            iANI8g7BmUG5mhpLwSmlJkiG5lrYtbGxIg/1tXuKcdRFUnqSxy5Y2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-13T01:34:34Z"
    mac: ENC[AES256_GCM,data:r/QowGDtZEOAhM1M6atc66FCE80Irkhe0N3NXc5MHa7Rwa0DSXJ+yYz7+svsFsEACw5OnwfHKXw7PvWm0rx7KYQotDulEnTmAtjkwLKUo/oXOLCUrFGMFrQw3qo2YWBPbyrMLxR+oi1+k1z4xs6VSLkbOg64imzfJFEpTOzX1sI=,iv:OL0u+KKutvD9dZgvoq9sVCu/2XVcdJYMPYgoOjqUNxE=,tag:rmAIo4HzRxb3lycennEkyw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
