#ENC[AES256_GCM,data:TA9kCJ5Xxdt0uwh47s7HdpTYZA==,iv:PiVZCoKXAlpOmnv25hW8HXSl3rp9H/G776upgOhIWUc=,tag:zzfWjd9UqJGbhHBXwkRdbg==,type:comment]
http:
    routers:
        minio:
            rule: ENC[AES256_GCM,data:RGl6NPAiSy58G0YNUcf+tqGbwCRzIRbXBQ==,iv:6sZQ6xmSnF071UHOEPHEvvVpkvGz3WbbIJ8itxajGm0=,tag:Y73Ip8aNkQ2Vo04BSA30vQ==,type:str]
            entrypoints: ENC[AES256_GCM,data:WxQpFE7T836X,iv:bSYBS17JXQ0Knz3tC9cwEKpkS9fn4KlZ67wE3c1dZhE=,tag:PE+i7CuUfJy9FzRVfvi7AA==,type:str]
            service: ENC[AES256_GCM,data:sLh8f9E=,iv:Z/wdRwJsEikboLPefLYo4HRUjOgKBGl85aq9iBEjsRw=,tag:bOkBw6WNsBLgpi+il3x99g==,type:str]
        teleport:
            rule: ENC[AES256_GCM,data:nW3G0U2gDMKS0smARaLITCSm7lsF3ySdQBz6WQ==,iv:gG4kEJbA4cg+wsWc0zogysHUYf1XbK1bkRcPtehwl1c=,tag:QPYB1X3iU6KO66DcYMHXmQ==,type:str]
            entrypoints: ENC[AES256_GCM,data:egJssEByctWt,iv:mHxIr4RjTMuOG6aGTFUsnM5ei6+WL5E6crWlxx3f9Qs=,tag:HkwY0jE0XuT7mM+jlhxXAA==,type:str]
            service: ENC[AES256_GCM,data:1+xOhFveS1w=,iv:3b3pcoBqzIiE8LHmnQV1MPtup4Q5OVQQxitVvBZ6h7Q=,tag:888YzrZLFQWLVnnJsxykfQ==,type:str]
        music:
            rule: ENC[AES256_GCM,data:1VGl8wLe1fQzcgt574IQlPMy+hllsj9AJQ==,iv:pgCHPTX6mvQOaeD5Unn6GdsUzDsPlUvayOdc5wTHaoE=,tag:L0AdIFcan8g7zMG/N1wP4Q==,type:str]
            entrypoints: ENC[AES256_GCM,data:80Fq7WhFE+wh,iv:QnUWfYFDwxHEdxXPfG0mjoxp6i+9B2Ye3czBMU+Cyl4=,tag:RrTLAfa4FTZKUIArVw5Eaw==,type:str]
            service: ENC[AES256_GCM,data:CFwwDeE=,iv:/K/dfMSl3csajLHLlW12KLCxhXjCtUlD9BUul8TESJY=,tag:7O8HlDdkcoJEcG3u/81N7g==,type:str]
    services:
        minio:
            loadBalancer:
                passHostHeader: ENC[AES256_GCM,data:wH9naQ==,iv:BrgrnksYNYvvYOsEe7wAODIvAX3/5cxdd+ReyGwGhF0=,tag:/Nv9qsxM0DAM7gBIQUtG+g==,type:bool]
                servers:
                    - url: ENC[AES256_GCM,data:E9syIr4sdeY7iJ8D87SYBHhXxSY5,iv:XGRvfhs+lHl5zxGtuy6hv5eB0H6k+z1sD0HFj3mbrqA=,tag:dC8QLQK77ELZ0/7M0o4jOw==,type:str]
        teleport:
            loadBalancer:
                passHostHeader: ENC[AES256_GCM,data:PQirig==,iv:3TbMhjiykgNJ83dLMPp/icqcBHJBdT11XefEyHrMcVg=,tag:kq3zQiM6H15YWgHhL1mAhw==,type:bool]
                servers:
                    - url: ENC[AES256_GCM,data:+aNHzSc3mOzvZsbMjrHYPa24CaHZTQ==,iv:Hpvci8283Ffl1ilFThAwTGzsg3Za18ILQXmzm6wLu/4=,tag:0oig/h3UTqp0iE9XuOkeAw==,type:str]
                serversTransport: ENC[AES256_GCM,data:txhKWU0pEwI=,iv:+9/cp3jgA3vefL8wU4CMywg/ylF1pTs4SisRm0O4GMs=,tag:U/kV9lWiKtJBrlwb7IhOnQ==,type:str]
        music:
            loadBalancer:
                passHostHeader: ENC[AES256_GCM,data:JPizFg==,iv:0hdD2KBUMpKUCxZWJgVwakyGASPx+BvHVbsqNYVUQRM=,tag:/QtJJ4hQudIxyeA2YaLvaw==,type:bool]
                servers:
                    - url: ENC[AES256_GCM,data:k2bmka4/uYiXl/I3X8bYOcB4L439,iv:APbH/LlJQ8xDZ8ecUAVl4+Ajn6/9bVOL3rm6blEOPYc=,tag:9gGqwZ3NnHSJBpzWNpxQJQ==,type:str]
    serversTransports:
        teleport:
            insecureSkipVerify: ENC[AES256_GCM,data:osL3TA==,iv:vMTXnvi2p2/Y0WJIPZIQG8ZSQyOaX81Aqp56Z+xbNig=,tag:BPo4NurM33Edwm/6MKcTiA==,type:bool]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13n6rctev7vwr2vuds9uqdh6anhvdvl2zt8gu9jp6mmvw2wukuqmqxz9ghv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFUlpWNkNkZUNBVm5lcmRt
            MGVIdkQzcDZuNWJRNHVaYTl6VTdFMm9qcDFrCko1YXMrRlp5bSt3Nm1BK2VhWncr
            N1N4MGdoNXYrSU9hN3lycGJna3BYejgKLS0tIGk1dk8rcWNCTUQ4T1lBM2lPZ251
            ZEtVekJXTE9RZUFZa3FVQTNEeUZrd2cKYTn+vYnvu6RUrPKvQn0QE5PrCruSYCpD
            iANI8g7BmUG5mhpLwSmlJkiG5lrYtbGxIg/1tXuKcdRFUnqSxy5Y2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-18T03:52:26Z"
    mac: ENC[AES256_GCM,data:0IPSSZlpnC5zpO81u93JyAPa4Zve7dhuwu3qbj0LgTI9qbquCmv/cXxsFBHnDo5SXywjTv0JjNYavDB4ZUIm5NCwlcxkp6lIL56ndt6yooMl0CDDs27SXYwP3rfyFV/0IFtr+o2ejlEKS/GbFDb6eyrobIFaTf6pui2Tk91GpeU=,iv:mBwaXvQf5AnVsGZOzcNSFWeBGYi42OYMgcAnkmGKYaI=,tag:OhBDTiSuEmFKU0+dob954g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
