#ENC[AES256_GCM,data:TA9kCJ5Xxdt0uwh47s7HdpTYZA==,iv:PiVZCoKXAlpOmnv25hW8HXSl3rp9H/G776upgOhIWUc=,tag:zzfWjd9UqJGbhHBXwkRdbg==,type:comment]
http:
    routers:
        music:
            rule: ENC[AES256_GCM,data:fLYV8p7pTzJ5JpPbx/VacK59kDMSAvHMHA==,iv:sjdi6U9s+mNp8rYzNUlQqqjSpGEz9Xa4adRB60JA7vc=,tag:YOMX8UjEpbY6wK+TuCH4/A==,type:str]
            entrypoints: ENC[AES256_GCM,data:tFtTy931S/VU,iv:LrvEPW1enrpxJbL0eMtEn2SmXNyjIwksZl4kf23kB98=,tag:4L4QO+1/byf2qLyf+NjWFw==,type:str]
            service: ENC[AES256_GCM,data:NFEPVEc=,iv:fik6Rt65L5Hd8KBTjANW7SofY9JJYPOYnJ660VJjHA4=,tag:Mb0ZUrohX1jwjYM/DxXKWw==,type:str]
        minio:
            rule: ENC[AES256_GCM,data:RGl6NPAiSy58G0YNUcf+tqGbwCRzIRbXBQ==,iv:6sZQ6xmSnF071UHOEPHEvvVpkvGz3WbbIJ8itxajGm0=,tag:Y73Ip8aNkQ2Vo04BSA30vQ==,type:str]
            entrypoints: ENC[AES256_GCM,data:WxQpFE7T836X,iv:bSYBS17JXQ0Knz3tC9cwEKpkS9fn4KlZ67wE3c1dZhE=,tag:PE+i7CuUfJy9FzRVfvi7AA==,type:str]
            service: ENC[AES256_GCM,data:sLh8f9E=,iv:Z/wdRwJsEikboLPefLYo4HRUjOgKBGl85aq9iBEjsRw=,tag:bOkBw6WNsBLgpi+il3x99g==,type:str]
    services:
        music:
            loadBalancer:
                passHostHeader: ENC[AES256_GCM,data:/Mk1tA==,iv:awTrNFQxiVAYHOk87/8dnog7aKvFZcF/PEdtNvZzRxo=,tag:QanVG0sEJhDYbfovnwJiQg==,type:bool]
                servers:
                    - url: ENC[AES256_GCM,data:R4JZK+OMSgzTWsO0n0A8aHA48WzO,iv:WiL4nzV/XkGJDzLqZIFDLqZthJd07ntWsJHNq7xWh7A=,tag:7aWwAMzRWyBHq44hrVqxsQ==,type:str]
        minio:
            loadBalancer:
                passHostHeader: ENC[AES256_GCM,data:wH9naQ==,iv:BrgrnksYNYvvYOsEe7wAODIvAX3/5cxdd+ReyGwGhF0=,tag:/Nv9qsxM0DAM7gBIQUtG+g==,type:bool]
                servers:
                    - url: ENC[AES256_GCM,data:E9syIr4sdeY7iJ8D87SYBHhXxSY5,iv:XGRvfhs+lHl5zxGtuy6hv5eB0H6k+z1sD0HFj3mbrqA=,tag:dC8QLQK77ELZ0/7M0o4jOw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13n6rctev7vwr2vuds9uqdh6anhvdvl2zt8gu9jp6mmvw2wukuqmqxz9ghv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFUlpWNkNkZUNBVm5lcmRt
            MGVIdkQzcDZuNWJRNHVaYTl6VTdFMm9qcDFrCko1YXMrRlp5bSt3Nm1BK2VhWncr
            N1N4MGdoNXYrSU9hN3lycGJna3BYejgKLS0tIGk1dk8rcWNCTUQ4T1lBM2lPZ251
            ZEtVekJXTE9RZUFZa3FVQTNEeUZrd2cKYTn+vYnvu6RUrPKvQn0QE5PrCruSYCpD
            iANI8g7BmUG5mhpLwSmlJkiG5lrYtbGxIg/1tXuKcdRFUnqSxy5Y2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-14T07:21:53Z"
    mac: ENC[AES256_GCM,data:v5cOQseuloyz6NHziXjVM/dtGfRx4kdsCBeDFsXZXAe+aZ2xgBBX7992WwXZriY3vme5u1rtoRe4jH0xFxVHknaxchs3aFo1ENt/4gD8x1fyNuTpFrX+IEKt12zfz0zsaLUqnVKd9YaS9/40yuGd8LhmqZ6C/qtDqppaNH5m3u4=,iv:KA+gWOWCbCYoJCqm9iz0Ad1cmoIsw5ARv2wg4mXVsSg=,tag:/hDK/rnYXfVldNkG3fi/Jg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
