---
- name: Ensure hass container info gathered
  community.docker.docker_container_info:
    name: hass
  register: result

- name: Ensure hass backup dir exists
  ansible.builtin.file:
    path: "{{ backup_dir }}/hass"
    state: directory

- name: Ensure hass backup
  when: result.exists
  block:
    - name: Ensure hass database backup
      community.postgresql.postgresql_db:
        login_user: "{{ postgres_user }}"
        login_password: "{{ postgres_password }}"
        host: localhost
        name: hass
        state: dump
        target: "{{ hass_db_backup }}"

    - name: Ensure hass config backup
      community.general.archive:
        path: "{{ hass_config_local_dir }}"
        dest: "{{ hass_config_backup }}"
