---
- name: Ensure cname file stat gathered
  ansible.builtin.stat:
    path: "{{ pihole_remote_cname_file }}"
  register: cname

- name: Ensure config dir exists
  ansible.builtin.file:
    path: "{{ pihole_remote_cname_file | dirname }}"
    state: directory
  when: not cname.stat.exists

- name: Ensure cname file exists
  ansible.builtin.file:
    path: "{{ pihole_remote_cname_file }}"
    state: touch
    mode: u=rw,g=rw,o=r
  when: not cname.stat.exists

- name: Ensure local cname file not exists
  ansible.builtin.file:
    path: "{{ pihole_cname_file }}"
    state: absent
  delegate_to: localhost
  changed_when: false

- name: Ensure cname file fetched
  ansible.builtin.fetch:
    src: "{{ pihole_remote_cname_file }}"
    dest: "{{ pihole_cname_file }}"
    flat: true
  changed_when: false

- name: Ensure fetch cname file permissions
  ansible.builtin.file:
    path: "{{ pihole_cname_file }}"
    state: file
    mode: "u=rw,g=rw,o=r"
    owner: root
    group: root
  delegate_to: localhost
  changed_when: false
