---
- name: Ensure core service tasks included
  ansible.builtin.include_tasks:
    file: core/main.yml
  tags: always

# - name: Ensure monitoring service tasks included
#  ansible.builtin.include_tasks:`
#    file: monitoring/main.yml
#  tags: always

- name: Ensure tools service tasks included
  ansible.builtin.include_tasks:
    file: storage/main.yml
  tags: always

- name: Ensure tools service tasks included
  ansible.builtin.include_tasks:
    file: tools/main.yml
  tags: always

- name: Ensure apps service tasks included
  ansible.builtin.include_tasks:
    file: apps/main.yml
  tags: always
