---
- name: Ensure music assistant vars included
  ansible.builtin.include_vars: music-assistant.yml

- name: Ensure music assistant facts configured
  ansible.builtin.set_fact:
    music_assistant_state: "{{ 'present' if music_assistant else 'absent' }}"

- name: Ensure music assistant image pulled
  community.docker.docker_image:
    name: "{{ music_assistant_image }}"
    source: pull
    state: "{{ music_assistant_state }}"

- name: Ensure music assistant data dir configured
  ansible.builtin.file:
    path: "/srv/music-assistant"
    state: "{{ 'directory' if music_assistant else 'absent' }}"

- name: Ensure music assistant container configured
  community.docker.docker_container:
    state: "{{ 'started' if music_assistant else 'absent' }}"
    image_name_mismatch: recreate
    name: music-assistant
    image: "{{ music_assistant_image }}"
    restart_policy: always
    network_mode: host
    privileged: true
    volumes:
      - /srv/music-assistant:/data
