---
- name: Ensure pihole image pulled
  community.docker.docker_image:
    name: "{{ pihole_image }}"
    source: pull

- name: Ensure pihole config dir exists
  ansible.builtin.file:
    path: "{{ pihole_dir }}/{{ item }}"
    state: directory
  with_items:
    - dnsmasq.d
    - etc

- name: Ensure pihole dnsmasq.d files copied
  ansible.builtin.copy:
    content: "{{ lookup('community.sops.sops', 'pihole/dnsmasq.d/' + item + '.sops') }}"
    dest: "{{ pihole_dir }}/dnsmasq.d/{{ item }}"
  loop:
    - 05-pihole-custom-cname.conf
    - 42-local-domain.conf
    - 99-k8s-gateway-forward.conf
  notify: Restart pihole dns

- name: Ensure pihole etc files copied
  ansible.builtin.copy:
    content: "{{ lookup('community.sops.sops', 'pihole/etc/' + item + '.sops') }}"
    dest: "{{ pihole_dir }}/etc/{{ item }}"
  loop:
    - custom.list
  notify: Restart pihole dns

- name: Ensure pihole container configured
  community.docker.docker_container:
    state: started
    image_name_mismatch: recreate
    name: pihole
    image: "{{ pihole_image }}"
    env: "{{ pihole_env }}"
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 1980:80
    restart_policy: always
    networks:
      - name: "{{ docker_network_name }}"
    volumes:
      - /srv/pihole/dnsmasq.d:/etc/dnsmasq.d:rw
      - /srv/pihole/etc:/etc/pihole:rw
