---
- name: Ensure db user configured
  community.postgresql.postgresql_user:
    user: "{{ db_user }}"
    password: "{{ db_pass }}"
    host: "{{ db_host }}"
    login_user: "{{ postgres_user }}"
    login_password: "{{ postgres_password }}"
    state: present
  when: not ansible_check_mode

- name: Ensure database configured
  community.postgresql.postgresql_db:
    name: "{{ db_name }}"
    host: "{{ db_host }}"
    owner: "{{ db_user }}"
    login_user: "{{ postgres_user }}"
    login_password: "{{ postgres_password }}"
  when: not ansible_check_mode
