---
- name: Ensure mosquitto tasks included
  ansible.builtin.include_tasks:
    file: mosquitto.yml
    apply:
      tags: mosquitto
  tags: mosquitto
  when: mosquitto

- name: Ensure squid tasks included
  ansible.builtin.include_tasks:
    file: squid.yml
    apply:
      tags: squid
  tags: squid
  when: squid

- name: Ensure docker network created
  community.docker.docker_network:
    name: "{{ docker_network_name }}"
    driver: bridge
  tags: always

- name: Get docker network info
  community.docker.docker_network_info:
    name: "{{ docker_network_name }}"
  register: docker_net_stat
  tags: always

- name: Set docker network facts
  ansible.builtin.set_fact:
    docker_network_exists: docker_net_stat.exists
  tags: always

- name: Ensure python postgres lib installed
  ansible.builtin.apt:
    name:
      - python3-psycopg2
      - python3-requests
    state: present
  tags: always

- name: Ensure pihole configured
  ansible.builtin.include_tasks:
    file: pihole.yml
    apply:
      tags: pihole
  tags: pihole

- name: Ensure postgres service configured
  ansible.builtin.include_tasks:
    file: postgres.yml
    apply:
      tags: postgres
  when: postgres
  tags: postgres

- name: Ensure traefik tasks included
  ansible.builtin.include_tasks:
    file: traefik.yml
    apply:
      tags: traefik
  tags: traefik

- name: Ensure tunnel tasks included
  ansible.builtin.include_tasks:
    file: tunnel.yml
    apply:
      tags: tunnel
  tags: tunnel
  when: tunnel
