---
- name: Ensure mosquitto installed
  ansible.builtin.apt:
    package: mosquitto
    state: present

- name: Ensure mosquitto service started
  ansible.builtin.service:
    name: mosquitto
    state: started

- name: Ensure mosquitto configuration copied
  ansible.builtin.copy:
    content: "{{ lookup('community.sops.sops', 'mosquitto/homelab.conf.sops') }}"
    dest: "/etc/mosquitto/conf.d/homelab.conf"

- name: Ensure mosquitto password copied
  ansible.builtin.copy:
    content: "{{ lookup('community.sops.sops', 'mosquitto/mosquitto.pwd.sops') }}"
    dest: "/etc/mosquitto/mosquitto.pwd"
    mode: o+rw,g+r,o+r
  notify: Restart mosquitto
