nextcloud: ENC[AES256_GCM,data:Vk7UbQ==,iv:8g14EB3sUEm9tMMsQDXl6vW33D+58jD2PBL4dYvU/pE=,tag:n7MK4kdeoAUfotAzfi8E6g==,type:bool]
nextcloud_env:
    POSTGRES_HOST: ENC[AES256_GCM,data:BJn6Pny/J3Qg,iv:q6QXTQoB4TJRBVfcgSgJnLK3s4+3t7FVoyLwRhNV0Vo=,tag:anOJFvfu0n05b5EYX0sTjA==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:ybNioMw2ykOk,iv:xc4SapF38SiuH9G2Qb2AYcjleuF3qNeu6XTv92+IeTU=,tag:0akGNCcEMAwpKtaKN3Vzdg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:z4SknLRQqbct,iv:ZgmliQmfOlieEIw7PkWF2ISfJaR+rYbVIZGK88GnaHM=,tag:Cle+4UXKn+1W1sJPthzeoA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:n/Br2lLrl07qnxlWEo0K/GxAYieBhawXH5oohAY4Rkw=,iv:fv8nL2lkzlJwZ3KtGcj6gDV2nclhfYzN6pcuhDeNW5c=,tag:vJZHYIk74vvP3bEh9Vvi4w==,type:str]
    NEXTCLOUD_ADMIN_USER: ENC[AES256_GCM,data:LgLa+A==,iv:TNJa8sbcSdmIdlk2yD+BgXHiXGpdy0Mtcwu8WYb5vOQ=,tag:3CDQkZw23Wt89itsI7Nxew==,type:str]
    NEXTCLOUD_ADMIN_PASSWORD: ENC[AES256_GCM,data:0pcNZwmE6PnNNsFOmNo=,iv:XWvVUVQPH2/pQFUghD9lDDsSQ4IIJzlrTifTN7LR2bE=,tag:Lc9PiJOZmjf2zJCB4Upzhw==,type:str]
    NEXTCLOUD_DATA_DIR: ENC[AES256_GCM,data:MZtwr5w=,iv:+ZFY8/eIgqOK/gXxqBDxhwfya0Yxam5XWlEe52j5gR0=,tag:Tmb4u3drhtwDK275e57brg==,type:str]
    NEXTCLOUD_TRUSTED_DOMAINS: ENC[AES256_GCM,data:iMLRg63EDOxeU5gESgRs6KQ=,iv:VrT7IzU3e0+ZUXNyJG0Ia5C7fNTENiE+3J8ALypCkNI=,tag:p4EXgcviZkGH8E9P+rzZew==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:ZaC23kYILs4oleTaruQ=,iv:SAaRRTI+6Y0H38Hhr3xFjNQ3DYzJ9ySDef2AAl0NdDY=,tag:EEbfq4IuL+Ad/S92fhhfHA==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:54ff,iv:5KHRgDQdQSd0nbl8f9xVZGTy7a2A8sAwl6bhEheuM1w=,tag:YUfxFNjh/j7q6ZblB0yUxw==,type:str]
    SMTP_NAME: ENC[AES256_GCM,data:LQ1l4TheCqIBW4N3+48=,iv:9gNJZmi0Fbgbke94uqSuWCQeSAYAetJxiShbYwWuscE=,tag:DZjK0DgrDkmuYmQrUrAD2w==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:0Ty7QlSBAqJGQ7cOXmy1TA==,iv:/zQxz+iasDs0ra8+gMROjzzKW+osNvUHta6YUrSMM/s=,tag:918M6LZbnxZ0KsgwK6BQ5A==,type:str]
    MAIL_FROM_ADDRESS: ENC[AES256_GCM,data:iJ3QXYLz,iv:Ky/D8rxFUofLNy8DKEq0Mw1g7XPeSNTO8w6T8ItAHgk=,tag:r7Co6Ob1oPkeSWiyrMKouA==,type:str]
    MAIL_DOMAIN: ENC[AES256_GCM,data:+lLhZSU3x3ntyXc=,iv:wieEvRoQr5GQyKf/BbOr9/xwI+oaSLz5eIefR8Yf+uQ=,tag:5/nynaUy/eCWaeAetrU+uw==,type:str]
    REDIS_HOST: ENC[AES256_GCM,data:dKnKncso2s3e,iv:hrmLB6e59MDKV7G9FbslK+k9RArN0EC//9xNcXvDob0=,tag:BlfRS7IBo6wwYc0wdAMGDg==,type:str]
    TRUSTED_PROXIES: ENC[AES256_GCM,data:dltcM3xHsBbH6TY=,iv:WBHQ1D2SU7O5ONhTMr30VecwFQmLhfT2GhiFtH8gQUQ=,tag:Lze4/uVUk9vy/rTk9BOe9A==,type:str]
    OVERWRITECLIURL: ENC[AES256_GCM,data:8FNVoXYRVbx+jW+i1E0/JmzG4IPHGbo67Q==,iv:M9BCBs3p/uAjzsyvW5en19TxlL4uyKdUHtlAwFCNUvE=,tag:GDiyBMRKoNWMpT7jJnFcQA==,type:str]
    PUID: ENC[AES256_GCM,data:auygfA==,iv:hrcjKlkLwLpTSmjsRCl0h3cOv4izOC16Nx+iqpsMbKk=,tag:cdKHkW/SIKI95MtkX0v4xQ==,type:str]
    PGID: ENC[AES256_GCM,data:7n5Z1w==,iv:cCWIfRGp/qGM2t5B/eXOm3PmOaVQO6ysNIUcigq6IWU=,tag:yYAQ7RNktQfQzQaQRDSIFw==,type:str]
    TZ: ENC[AES256_GCM,data:KGTVroOLhg==,iv:M8Z0J/qhT1ISYyvDfesB8ZHnrALQ8PHtBgngBjJbzI0=,tag:OLAdaEtcHedgnByk4GlfDw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13n6rctev7vwr2vuds9uqdh6anhvdvl2zt8gu9jp6mmvw2wukuqmqxz9ghv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjRlpSZGxjR1prbjgyeFdB
            NFhOblgrUjYzbDVIYTRkOGpCYUpTaDBxVFhZClM5ZmxGai9IaGRQQjRqV2hMSnN5
            N0pkaVRGWU40SmpsZk14eG11UG52eUEKLS0tIGtReFZrWkRHZ2JycEZRR05jcUVJ
            cXFQSERNUmdUNWZEVkxJVTZhbklCb2cKgFB3UAphLa93eAgJ29v9pSDKgQmopPEI
            UTmgq9CHlSKYjOP2AatgMs7iWCYRigYEPAEzOC7XtqSMbM5s9qiiSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-14T08:08:02Z"
    mac: ENC[AES256_GCM,data:v1O3o5/Ysb4gKPY+9UACls5z+OhkbmQ6ArU8zusq2tIsN3cknPoj/2FhUqBmKsDnhfMeKonsna88Zd4OBxQeIcJBil3qYWvFzjrk4DPCIiOATl5xuLD3M4zy21Y23flIOPNiCMhgW5Aog8GYU9xOHKULilXfT60FrOd27KzIx5E=,iv:V0Hw+62OlLCdmFM8VMqTa87wm1lz101H/ythOXyQJbs=,tag:Ys8osBzXqmFfYK58RyKD3g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
