teleport: ENC[AES256_GCM,data:8biDPzQ=,iv:nk9nea4sPyxwxr4TJ8Icr1+jTZvTp88j30GW1KqObDE=,tag:qWhQBWYttlGxtfO2XGgaMA==,type:bool]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13n6rctev7vwr2vuds9uqdh6anhvdvl2zt8gu9jp6mmvw2wukuqmqxz9ghv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2WHNCOVMzdHQ5NTljS21B
            WGFjOS9CbEJaazcyT1hlWENkR0NBOHBheDFvCmc1MHVFN1c4QTh4cEl3U0FVN1hj
            b0ZOajBWU0I1MWRMVE9keG10d3JJaUEKLS0tIEVrSEE0MG1ESWE3alNlVFo0Mnp4
            a0swUGp2MUgrMUFJbzhVQ2pIb0VEM0kK1VmyKrxiZcWf++CAXLfIMzGBosX5NqNh
            qOOkC+9uB6tQMhNgZfqg3fpFh3OcS3ODxYcWTjBexeKvcxELcnvbQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-07T04:18:11Z"
    mac: ENC[AES256_GCM,data:cWbf2FCgtNKnLHDk4oBiKq9iGcLKfWApK1J5vK5Vj/8p24sC0uM82VxMB1vDaLq1ETMMFpCaPVr5TVp6GlWxNN6NkvVvQ6LPTZtZDpbSz/OEIv43gHTjCpaCxwokqVufbZaB4pGRAH3/AUq/JN96Th+FVavxvezHiFXIrNHbwE0=,iv:du1IJ1kYDHhHJcQKf0cQTwtWcIsjrt5CeSIt3VRI5SQ=,tag:tF6U0yc3uCHDPjxg9yf2fQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
